encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.entry, name="entry"),
    path("newpage/", views.newpage, name="newpage"),
    path("edit/<str:name>/", views.edit, name="edit"),
    path("random/", views.random, name="random"),
    path("search/", views.search, name="search"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect

from django.http import Http404

from django.urls import reverse

from django import forms

from . import util

from random import choice

import markdown2


class NewTaskForm(forms.Form):
    title = forms.CharField(label="Entry Title:", max_length=100)
    content = forms.CharField(widget=forms.Textarea ,label="Content:")


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry(request, name):
    get = util.get_entry(name)
    if get is not None:
        html = markdown2.markdown(get)
        return render(request, "encyclopedia/entry.html", {
            "title": html,
            "name": name.capitalize(),
        })
    else:
        list = [list for list in util.list_entries() if name.lower() in list.lower()]
        if not list:
            raise Http404("The requested page does not exist")
        return render(request, "encyclopedia/list.html", {
            "list": list,
            "name": name,
        })

def newpage(request):
    # return render(request, "encyclopedia/newpage.html")
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if util.get_entry(title):
                form.add_error("title",f"An entry with title:{title} already exists")
                return render(request, "encyclopedia/newpage.html", {
                    "form": form
                })
            util.save_entry(title, content)
            return redirect("encyclopedia:entry", name=title)
        else:
            return render(request, "encyclopedia/newpage.html", {
                "form": form
            })

    return render(request, "encyclopedia/newpage.html", {
        "form": NewTaskForm()
    })

def edit(request, name):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]   
            util.save_entry(title, content)
            return redirect("encyclopedia:entry", name=title)
    entry_content = util.get_entry(name)
    form = NewTaskForm(initial={'title': name, 'content': entry_content})
    return render(request, "encyclopedia/edits.html", {
        "form": form,
        "name": name,
    })

def random(request):
    new = choice(util.list_entries())
    return redirect("encyclopedia:entry", name=new)


def search(request):
    query = request.GET.get('q')
    if query:
        return redirect('encyclopedia:entry', name=query)
    return redirect('encyclopedia:index')

encyclopedia/templates/encyclopedia/edits.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <form action="{% url 'encyclopedia:edit' name %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save Changes">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ name }}
{% endblock %}

{% block body %}
    <div>
        {{ title|safe }}
    </div>
    <a href="{% url 'encyclopedia:edit' name=name %}">Edit {{ name }}</a>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    <input type="submit" class="search" value="Search">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/list.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    Search Results For: {{ name }}
    <ul>
        {% for lis in list %}
        <li>
            <a href="{% url 'encyclopedia:entry' lis %}">{{ lis }}
        </li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <form action="{% url 'encyclopedia:newpage' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}